# Generated by Django 3.0.6 on 2020-05-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='last_name',
        ),
    ]
