# Generated by Django 3.0.6 on 2020-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_designerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='first_name',
            field=models.CharField(default='temporary first name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='last_name',
            field=models.CharField(default='temporary last name', max_length=30),
            preserve_default=False,
        ),
    ]
