# Generated by Django 3.0.6 on 2020-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200513_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='register_designer',
            field=models.BooleanField(blank=True, default='True'),
            preserve_default=False,
        ),
    ]
