# Generated by Django 3.0.6 on 2020-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200515_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerprofile',
            name='register_designer',
            field=models.BooleanField(blank=True),
        ),
    ]
