# Generated by Django 3.0.6 on 2020-05-15 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prints', '0003_auto_20200514_1415'),
        ('profiles', '0008_auto_20200515_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignerProfile',
            new_name='RegisteredUserProfile',
        ),
        migrations.AlterModelOptions(
            name='registereduserprofile',
            options={'verbose_name': 'Registered User Profile'},
        ),
    ]
