# Generated by Django 3.0.6 on 2020-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadPrint',
            new_name='Print',
        ),
    ]
