# Generated by Django 3.0.6 on 2020-05-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200519_1106'),
        ('prints', '0003_auto_20200514_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_key', to='profiles.RegisteredUserProfile'),
        ),
    ]
