# Generated by Django 3.0.6 on 2020-05-14 20:42

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='00', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='00', max_length=10),
            preserve_default=False,
        ),
    ]
