# Generated by Django 3.0.6 on 2020-05-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200516_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='postcode',
        ),
    ]
